import {
  PLACEMENT_TYPE_HERO_EDITING,
  PLACEMENT_TYPE_HERO_SPAWN,
} from "@/helpers/consts";

export const BugLevel3 = {
  theme: "YELLOW",
  tilesWidth: 10,
  tilesHeight: 10,
  placements: [
    { type: "WALL", x: 2, y: 2 },
    { type: "WALL", x: 3, y: 2 },
    { type: "WALL", x: 4, y: 2 },
    { type: "WALL", x: 1, y: 4 },
    { type: "WALL", x: 1, y: 3 },
    { type: "WALL", x: 1, y: 2 },
    { type: "WALL", x: 2, y: 3 },
    { type: "WALL", x: 2, y: 5 },
    { type: "WALL", x: 1, y: 5 },
    { type: "WALL", x: 3, y: 5 },
    { type: "WALL", x: 4, y: 5 },
    { type: "WALL", x: 6, y: 5 },
    { type: "WALL", x: 6, y: 4 },
    { type: "WALL", x: 6, y: 3 },
    { type: "WALL", x: 6, y: 2 },
    { type: "WALL", x: 5, y: 2 },
    { type: "ICE", x: 3, y: 4, corner: "BOTTOM_RIGHT" },
    { type: "ICE", x: 3, y: 3, corner: "TOP_LEFT" },
    { type: "ICE", x: 4, y: 4, corner: "BOTTOM_LEFT" },
    { type: "ICE", x: 4, y: 3, corner: "TOP_RIGHT" },
    { x: 2, y: 4, type: PLACEMENT_TYPE_HERO_SPAWN },
    { x: 2, y: 4, type: PLACEMENT_TYPE_HERO_EDITING },
    { x: 4, y: 9, type: "GOAL" },
    { type: "ICE", x: 5, y: 4, corner: "TOP_RIGHT" },
    { type: "ICE", x: 5, y: 5 },
    { type: "ICE", x: 5, y: 6 },
    { type: "ICE", x: 3, y: 8, corner: "BOTTOM_LEFT" },
    { type: "ICE", x: 4, y: 6 },
    { type: "ICE", x: 3, y: 7 },
    { type: "ICE", x: 3, y: 6, corner: "TOP_LEFT" },
    { type: "ICE", x: 4, y: 8 },
    { type: "WATER", x: 5, y: 8 },
    { type: "ICE", x: 6, y: 6 },
    { type: "ICE", x: 7, y: 6 },
    { type: "ICE", x: 8, y: 6 },
    { type: "ICE", x: 9, y: 6 },
    { type: "FLOUR", x: 8, y: 6 },
    { type: "ICE_PICKUP", x: 10, y: 8 },
    { type: "FLOUR", x: 3, y: 7 },
    { type: "WATER", x: 2, y: 8 },
    { type: "ICE", x: 5, y: 7, corner: "TOP_LEFT" },
    { type: "ICE", x: 4, y: 7 },
  ],
};
