import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_HERO_SPAWN,
  PLACEMENT_TYPE_HERO_EDITING,
} from "../helpers/consts";
const DemoLevel6 = {
  theme: "GRAY",
  tilesWidth: 21,
  tilesHeight: 13,
  placements: [
    { x: 2, y: 2, type: PLACEMENT_TYPE_HERO_SPAWN },
    { x: 2, y: 2, type: PLACEMENT_TYPE_HERO_EDITING },
    { type: "GOAL", x: 19, y: 2 },
    { type: "KEY", x: 2, y: 6, color: "BLUE" },
    { type: "LOCK", x: 8, y: 11, color: "GREEN" },
    { type: "LOCK", x: 9, y: 12, color: "GREEN" },
    { type: "LOCK", x: 10, y: 11, color: "GREEN" },
    { type: "KEY", x: 10, y: 6, color: "BLUE" },
    { type: "KEY", x: 13, y: 9, color: "BLUE" },
    { type: "FLOUR", x: 10, y: 2 },
    { type: "FLOUR", x: 13, y: 4 },
    { type: "FLOUR", x: 17, y: 13 },
    { type: "FLOUR", x: 20, y: 12 },
    { type: "WALL", x: 1, y: 4 },
    { type: "WALL", x: 1, y: 8 },
    { type: "WALL", x: 2, y: 8 },
    { type: "WALL", x: 2, y: 10 },
    { type: "WALL", x: 2, y: 12 },
    { type: "WALL", x: 3, y: 4 },
    { type: "WALL", x: 3, y: 8 },
    { type: "WALL", x: 4, y: 1 },
    { type: "WALL", x: 4, y: 3 },
    { type: "WALL", x: 4, y: 4 },
    { type: "WALL", x: 4, y: 5 },
    { type: "WALL", x: 4, y: 6 },
    { type: "WALL", x: 4, y: 7 },
    { type: "WALL", x: 4, y: 8 },
    { type: "WALL", x: 4, y: 10 },
    { type: "WALL", x: 4, y: 12 },
    { type: "WALL", x: 5, y: 4 },
    { type: "WALL", x: 5, y: 8 },
    { type: "WALL", x: 6, y: 4 },
    { type: "WALL", x: 6, y: 8 },
    { type: "WALL", x: 7, y: 4 },
    { type: "WALL", x: 7, y: 8 },
    { type: "WALL", x: 8, y: 1 },
    { type: "WALL", x: 8, y: 3 },
    { type: "WALL", x: 8, y: 4 },
    { type: "WALL", x: 8, y: 5 },
    { type: "WALL", x: 8, y: 7 },
    { type: "WALL", x: 8, y: 8 },
    { type: "WALL", x: 8, y: 10 },
    { type: "WALL", x: 8, y: 12 },
    { type: "WALL", x: 9, y: 4 },
    { type: "WALL", x: 9, y: 8 },
    { type: "WALL", x: 10, y: 4 },
    { type: "WALL", x: 10, y: 8 },
    { type: "WALL", x: 10, y: 10 },
    { type: "WALL", x: 10, y: 12 },
    { type: "WALL", x: 11, y: 4 },
    { type: "WALL", x: 11, y: 8 },
    { type: "WALL", x: 12, y: 1 },
    { type: "WALL", x: 12, y: 3 },
    { type: "WALL", x: 12, y: 4 },
    { type: "WALL", x: 12, y: 5 },
    { type: "WALL", x: 12, y: 6 },
    { type: "WALL", x: 12, y: 7 },
    { type: "WALL", x: 12, y: 8 },
    { type: "WALL", x: 12, y: 9 },
    { type: "WALL", x: 12, y: 10 },
    { type: "WALL", x: 12, y: 11 },
    { type: "WALL", x: 12, y: 12 },
    { type: "WALL", x: 12, y: 13 },
    { type: "WALL", x: 14, y: 7 },
    { type: "WALL", x: 17, y: 11 },
    { type: "WALL", x: 18, y: 12 },
    { type: "WALL", x: 18, y: 13 },
    { type: "WALL", x: 19, y: 7 },
    { type: "WALL", x: 19, y: 10 },
    { type: "WALL", x: 21, y: 10 },
    { type: "TELEPORT", x: 6, y: 2 },
    { type: "TELEPORT", x: 6, y: 6 },
    { type: "TELEPORT", x: 3, y: 11 },
    { type: "TELEPORT", x: 9, y: 11 },
    { type: "CONVEYOR", x: 2, y: 11, direction: "LEFT" },
    { type: "CONVEYOR", x: 3, y: 10, direction: "UP" },
    { type: "CONVEYOR", x: 3, y: 12, direction: "DOWN" },
    { type: "CONVEYOR", x: 4, y: 11, direction: "RIGHT" },
    { type: "CONVEYOR", x: 13, y: 7, direction: "DOWN" },
    { type: "CONVEYOR", x: 13, y: 8, direction: "DOWN" },
    { type: "CONVEYOR", x: 16, y: 5, direction: "LEFT" },
    { type: "CONVEYOR", x: 17, y: 5, direction: "LEFT" },
    { type: "FIRE_PICKUP", x: 20, y: 2 },
    { type: "FIRE", x: 13, y: 3 },
    { type: "FIRE", x: 13, y: 5 },
    { type: "FIRE", x: 13, y: 11 },
    { type: "FIRE", x: 14, y: 4 },
    { type: "SWITCH_DOOR", x: 17, y: 8, isRaised: false },
    { type: "SWITCH", x: 15, y: 13 },
    { type: "WATER", x: 16, y: 1 },
    { type: "WATER", x: 16, y: 2 },
    { type: "WATER", x: 16, y: 3 },
    { type: "WATER", x: 16, y: 4 },
    { type: "WATER", x: 16, y: 6 },
    { type: "WATER", x: 16, y: 7 },
    { type: "WATER", x: 17, y: 6 },
    { type: "WATER", x: 17, y: 7 },
    { type: "WATER", x: 17, y: 9 },
    { type: "WATER", x: 17, y: 10 },
    { type: "WATER", x: 18, y: 9 },
    { type: "WATER", x: 18, y: 10 },
    { type: "WATER", x: 18, y: 11 },
    { type: "ICE", x: 18, y: 8 },
    { type: "ICE", x: 19, y: 8 },
    { type: "ICE", x: 19, y: 9 },
    { type: "ICE", x: 20, y: 7 },
    { type: "ICE", x: 20, y: 8 },
    { type: "ICE", x: 20, y: 9 },
    { type: "THIEF", x: 12, y: 2 },
    { type: "WALL", x: 14, y: 8 },
    { type: "WALL", x: 14, y: 9 },
    { type: "WALL", x: 14, y: 10 },
    { type: "CONVEYOR", x: 13, y: 10, direction: "DOWN" },
    { type: "CONVEYOR", x: 13, y: 9, direction: "DOWN" },
    { type: "LOCK", x: 8, y: 2, color: "GREEN" },
    { type: "LOCK", x: 9, y: 10, color: "GREEN" },
  ],
};
export default DemoLevel6;
