import { TILES } from "./tiles";

export const CELL_SIZE = 16;
export const Z_INDEX_LAYER_SIZE = 10;

export const SPRITE_SHEET_SRC = "/ciabattas-revenge-sprites.png";

export const PLACEMENT_TYPE_HERO = "HERO";
export const PLACEMENT_TYPE_HERO_SPAWN = "HERO_SPAWN";
export const PLACEMENT_TYPE_HERO_EDITING = "HERO_EDITING";
export const PLACEMENT_TYPE_GOAL = "GOAL";
export const PLACEMENT_TYPE_GOAL_ENABLED = "GOAL_ENABLED";
export const PLACEMENT_TYPE_WALL = "WALL";
export const PLACEMENT_TYPE_FLOUR = "FLOUR";
export const PLACEMENT_TYPE_CELEBRATION = "CELEBRATION";

export const PLACEMENT_TYPE_LOCK = "LOCK";
export const PLACEMENT_TYPE_KEY = "KEY";

export const PLACEMENT_TYPE_WATER = "WATER";
export const PLACEMENT_TYPE_FIRE = "FIRE";
export const PLACEMENT_TYPE_ICE = "ICE";
export const PLACEMENT_TYPE_CONVEYOR = "CONVEYOR";
export const PLACEMENT_TYPE_TELEPORT = "TELEPORT";
export const PLACEMENT_TYPE_THIEF = "THIEF";

export const PLACEMENT_TYPE_WATER_PICKUP = "WATER_PICKUP";
export const PLACEMENT_TYPE_FIRE_PICKUP = "FIRE_PICKUP";
export const PLACEMENT_TYPE_ICE_PICKUP = "ICE_PICKUP";

export const PLACEMENT_TYPE_GROUND_ENEMY = "GROUND_ENEMY";
export const PLACEMENT_TYPE_ENEMY_LEFT_SPAWN = "ENEMY_LEFT_SPAWN";
export const PLACEMENT_TYPE_ENEMY_RIGHT_SPAWN = "ENEMY_RIGHT_SPAWN";
export const PLACEMENT_TYPE_ENEMY_DOWN_SPAWN = "ENEMY_DOWN_SPAWN";
export const PLACEMENT_TYPE_ENEMY_UP_SPAWN = "ENEMY_UP_SPAWN";

export const PLACEMENT_TYPE_FLYING_ENEMY = "FLYING_ENEMY";
export const PLACEMENT_TYPE_ENEMY_FLYING_LEFT_SPAWN = "ENEMY_FLYING_LEFT_SPAWN";
export const PLACEMENT_TYPE_ENEMY_FLYING_RIGHT_SPAWN =
  "ENEMY_FLYING_RIGHT_SPAWN";
export const PLACEMENT_TYPE_ENEMY_FLYING_DOWN_SPAWN = "ENEMY_FLYING_DOWN_SPAWN";
export const PLACEMENT_TYPE_ENEMY_FLYING_UP_SPAWN = "ENEMY_FLYING_UP_SPAWN";

export const PLACEMENT_TYPE_ROAMING_ENEMY = "ROAMING_ENEMY";
export const PLACEMENT_TYPE_ENEMY_ROAMING_SPAWN = "ENEMY_ROAMING_SPAWN";
export const PLACEMENT_TYPE_CIABATTA = "CIABATTA";
export const PLACEMENT_TYPE_CIABATTA_SPAWN = "CIABATTA_SPAWN";

export const PLACEMENT_TYPE_SWITCH_DOOR = "SWITCH_DOOR";
export const PLACEMENT_TYPE_SWITCH = "SWITCH";

export const DIRECTION_LEFT = "LEFT" as const;
export const DIRECTION_RIGHT = "RIGHT" as const;
export const DIRECTION_UP = "UP" as const;
export const DIRECTION_DOWN = "DOWN" as const;

export const DEATH_TYPE_CLOCK = "CLOCK";

// bodyPlacement 可以踩過的 placements，用來塗顏色顯示最短路徑
export const GROUND_PLACEMENT_TYPES = [
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_GOAL_ENABLED,
  PLACEMENT_TYPE_WALL
];

type DirectionUpdateMapType = {
  [key: string]: { x: number; y: number };
};

export const directionUpdateMap: DirectionUpdateMapType = {
  [DIRECTION_LEFT]: { x: -1, y: 0 },
  [DIRECTION_RIGHT]: { x: 1, y: 0 },
  [DIRECTION_UP]: { x: 0, y: -1 },
  [DIRECTION_DOWN]: { x: 0, y: 1 },
} as const;

export const directions = [
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
];

export const BODY_SKINS = {
  NORMAL: "NORMAL",
  WATER: "WATER",
  ICE: "ICE",
  CONVEYOR: "CONVEYOR",
  FIRE: "FIRE",
  TELEPORT: "TELEPORT",
  DEATH: "DEATH",
  SCARED: "SCARED",
};

export const ICE_CORNERS = {
  TOP_LEFT: "TOP_LEFT",
  TOP_RIGHT: "TOP_RIGHT",
  BOTTOM_LEFT: "BOTTOM_LEFT",
  BOTTOM_RIGHT: "BOTTOM_RIGHT",
} as const;

export const HERO_RUN_1 = "HERO_RUN_1";
export const HERO_RUN_2 = "HERO_RUN_2";

export const LOCK_KEY_COLORS = {
  BLUE: "BLUE",
  GREEN: "GREEN",
} as const;

export const LEVEL_THEMES = {
  YELLOW: "YELLOW",
  BLUE: "BLUE",
  GREEN: "GREEN",
  PINK: "PINK",
  GRAY: "GRAY",
};

export const THEME_ARRAY = [
  LEVEL_THEMES.YELLOW,
  LEVEL_THEMES.BLUE,
  LEVEL_THEMES.GREEN,
  LEVEL_THEMES.PINK,
  LEVEL_THEMES.GRAY,
];

// 遊戲場景背景延伸色
export const THEME_BACKGROUNDS = {
  [LEVEL_THEMES.YELLOW]: "#2f2808",
  [LEVEL_THEMES.BLUE]: "#3d4c67",
  [LEVEL_THEMES.GREEN]: "#2f2808",
  [LEVEL_THEMES.PINK]: "#673d5e",
  [LEVEL_THEMES.GRAY]: "#96a1c7",
};
// 定義每一個主題的牆壁(上下左右)和地板
export const THEME_TILES_MAP = {
  [LEVEL_THEMES.YELLOW]: {
    FLOOR: "1x1",
    TOP: "1x0",
    LEFT: "0x1",
    RIGHT: "2x1",
    BOTTOM: "1x2",
    WALL: "0x2",
  },
  [LEVEL_THEMES.BLUE]: {
    FLOOR: "4x1",
    TOP: "4x0",
    LEFT: "3x1",
    RIGHT: "5x1",
    BOTTOM: "4x2",
    WALL: "3x2",
  },
  [LEVEL_THEMES.GREEN]: {
    FLOOR: "7x1",
    TOP: "7x0",
    LEFT: "6x1",
    RIGHT: "8x1",
    BOTTOM: "7x2",
    WALL: "6x2",
  },
  [LEVEL_THEMES.PINK]: {
    FLOOR: "10x1",
    TOP: "10x0",
    LEFT: "9x1",
    RIGHT: "11x1",
    BOTTOM: "10x2",
    WALL: "9x2",
  },
  [LEVEL_THEMES.GRAY]: {
    FLOOR: "13x1",
    TOP: "13x0",
    LEFT: "12x1",
    RIGHT: "14x1",
    BOTTOM: "13x2",
    WALL: "12x2",
  },
};

export const PLACEMENT_TYPES_CODE = {
  EMPTY: "0",
  DEFAULT_HERO_CODE: "h",
  HERO: "H", // "h" 代表該模板房間入被選為出生房間其預設出生位置
  DEFAULT_GOAL_CODE: "g",
  GOAL: "G", //  "g" 代表該模板房間入被選為終點房間其預設終點位置
  WALL: "1", // 1-50, 1-25, 1-75  使用 dash 後面接數字代表該物體出現機率，例如 1-50 代表 WALL 出現機率 50%

  WATER: "W",
  WATER_PICKUP: "WP", // 可以使用 & 在同一位置上出現兩種物體 例如在該冰上有50%機率出現 WATER_PICKUP 則 "WP-50&I"
  FIRE: "F",
  FIRE_PICKUP: "FP",
  ICE: "I",
  ICE_BOTTOM_RIGHT: "I_BR",
  ICE_BOTTOM_LEFT: "I_BL",
  ICE_TOP_LEFT: "I_TL",
  ICE_TOP_RIGHT: "I_TR",

  ICE_PICKUP: "IP",

  FLOUR: "M",
  LOCK: "L",
  KEY: "K",
  CONVEYOR: "C",
  // CONVEYOR_RIGHT: "C_R",
  // CONVEYOR_LEFT: "C_L",
  // CONVEYOR_UP: "C_U",
  // CONVEYOR_DOWN: "C_D",

  TELEPORT: "T",
  THIEF: "R", // Reset tile
  SWITCH_DOOR: "SD",
  SWITCH_DOOR_Default_Raised: "SD_1",
  SWITCH_DOOR_Default_Without_Raised: "SD_0",
  SWITCH: "S",

  GROUND_ENEMY: "GE",
  // 預設 ENEMY 是水平(左右)移動 也可以設置  GE_D (DOWN)或是 GE_U (UP) 垂直走
  FLYING_ENEMY: "FE", // 同理 GROUND_ENEMY ，FE_D, FE_U
  ROAMING_ENEMY: "RE", // ROAMING_ENEMY 是隨機行走的
  CIABATTA: "BOSS",
};

// 可以踩在腳下的 placements
export const BOTTOM_PLACEMENTS = [
  PLACEMENT_TYPES_CODE.WATER,
  PLACEMENT_TYPES_CODE.FIRE,
  PLACEMENT_TYPES_CODE.ICE,
  PLACEMENT_TYPES_CODE.CONVEYOR,
  PLACEMENT_TYPES_CODE.THIEF,
  PLACEMENT_TYPES_CODE.TELEPORT,
  PLACEMENT_TYPES_CODE.SWITCH,
];
// 可以獲取的 placements
export const FLOATING_PLACEMENTS = [
  PLACEMENT_TYPES_CODE.KEY,
  PLACEMENT_TYPES_CODE.FLOUR,
  PLACEMENT_TYPES_CODE.WATER_PICKUP,
  PLACEMENT_TYPES_CODE.FIRE_PICKUP,
  PLACEMENT_TYPES_CODE.ICE_PICKUP,
];

export const SELECTED_CATEGORY_MAP: { [key: string]: string[] } = {
  basics: [TILES.HERO_SPAWN, TILES.GOAL_ENABLED],
  tiles: [
    TILES.WALL,
    TILES.CONVEYOR_DOWN,
    TILES.CONVEYOR_LEFT,
    TILES.CONVEYOR_RIGHT,
    TILES.CONVEYOR_UP,
    TILES.WATER1,
    TILES.ICE,
    TILES.ICE_BOTTOM_LEFT,
    TILES.ICE_BOTTOM_RIGHT,
    TILES.ICE_TOP_LEFT,
    TILES.ICE_TOP_RIGHT,
    TILES.FIRE1,
    TILES.THIEF,
    TILES.TELEPORT1,
    TILES.BLUE_LOCK,
    TILES.GREEN_LOCK,
    TILES.SWITCH,
    TILES.SWITCH_DOOR_OUTLINE,
    TILES.SWITCH_DOOR_SOLID,
  ],
  pickups: [
    TILES.FLOUR,
    TILES.ICE_PICKUP,
    TILES.FIRE_PICKUP,
    TILES.WATER_PICKUP,
    TILES.BLUE_KEY,
    TILES.GREEN_KEY,
  ],
  enemies: [
    TILES.ENEMY_UP_SPAWN,
    TILES.ENEMY_DOWN_SPAWN,
    TILES.ENEMY_LEFT_SPAWN,
    TILES.ENEMY_RIGHT_SPAWN,
    TILES.ENEMY_FLYING_UP_SPAWN,
    TILES.ENEMY_FLYING_DOWN_SPAWN,
    TILES.ENEMY_FLYING_LEFT_SPAWN,
    TILES.ENEMY_FLYING_RIGHT_SPAWN,
    TILES.ENEMY_ROAMING_SPAWN,
    TILES.CIABATTA_SPAWN,
  ],
};
